### ISSUE TITLE
Website https://free-e-target.com/about/ has broken link to targettalk

### ISSUE THREAD

**Issue by danmoy** [ten-point-nine/freETarget#10]
Web page reads:

```
Join the conversation on TargetTalk.org. freETarget
```

It links to TargetTalk.org.or, which does not exist.  I don't know if the webpage's code is on this github or not, but the change is thus:

```
<a href="http://targettalk.org.or">TargetTalk.org</a>
```

Should instead be:

```
<a href="http://targettalk.org">TargetTalk.org</a>
```

**Comment by danmoy** [comment]
Actually while we're at it, you should probably prefer to link to `https://targettalk.org`, since TargetTalk doesn't have automatic redirect to https set up.

**Comment by AzmodanRO** [comment]
done. link fixed. now it points to the freetarget thread
