### ISSUE TITLE
Lower priority: file naming

### ISSUE THREAD

**Issue by danmoy** [ten-point-nine/freETarget#12]
Hey very cool project you have here.

One minor note on the c# code at least is the readability of filenames.  For example you have a bunch of files named [form1](https://github.com/ten-point-nine/freETarget/blob/master/Software/C%23/freETarget/Form1.cs), form2, form3, form4, form5, etc.  To an external contributor reading the code, it's pretty arbitrary to navigate if the name of the file doesn't give any indication as to what is in the file.

**Comment by AzmodanRO** [comment]
done
