### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by Muammer06** [ten-point-nine/freETarget#13]
hey allan, I am student at university and our team make some machine learning things about 
shooting accuracy so we need record shootings like around 1000-1500. And I can just found your projects but I need help for setup. I can't understand to using which type of sensors and arduino coding. Also I am the new in coding like 3 months. if you help me thank you. I need this project in one month. thanks

**Comment by AzmodanRO** [comment]
go to https://free-e-target.com/ to learn more about the project.

**Comment by ten-point-nine** [comment]
Where are you located?

I have some detector boards I could send.

You would need for add your own processing boards.

Allan

**Comment by Muammer06** [comment]
Hey, I am living in Ankara,Turkey. I am student at Hacettepe University and I am so glad about these boards. I have esp32 and arduino. Thank you again. Where we can talk my email is= muammert9@gmail.com
