### ISSUE TITLE
error when debugging with latest software

### ISSUE THREAD

**Issue by TigraTT** [ten-point-nine/freETarget#14]
dear all,
i have received the boards and i get a working setup very fast.
Now i want to make some tests with the pc software by debug in visual studio, but if i do not have connected a arduino board there is always an error when trying to enter the settings page.
This error came up even when the Targetsimulator is running and the COM ports are connected crossover.
With an older version of the pc software everything works fine.
![Azmo_failure](https://user-images.githubusercontent.com/66295999/110791985-23e51e00-8273-11eb-8045-efce184f86c1.png)

**Comment by AzmodanRO** [comment]
committed fix to master branch
