### ISSUE TITLE
Android / OS X / iOS versions possible? 

### ISSUE THREAD

**Issue by javaduke** [ten-point-nine/freETarget#16]
Folks, I know it's a long shot but I'm wondering if there are any plans to port the UI part to other platforms such as Linux/Android? There's a plenty of cheap Android tablets available on Amazon, and they would make an excellent display that shooters can set up on the bench, instead of using a bulkier and more expensive Windows PC. Please consider releasing a Linux/Android version.

**Comment by AzmodanRO** [comment]
sorry.. not at the moment.
UI frameworks for android/iOS are much harder to work with and less feature rich that Windows Forms .NET
if there is anyone with plenty of skill+knowledge+time, please feel free to try
