### ISSUE TITLE
PC Program Upgrade

### ISSUE THREAD

**Issue by ten-point-nine** [ten-point-nine/freETarget#18]
Just a couple of questions if you don’t mind.
1, can the pc software be updated without being deleted and redownloded?
2, is there a way to save or export the shooting data?

**Comment by AzmodanRO** [comment]
1. yes. i found the flag that allows to uninstall the previous version, when installing the new one. the new version must still be downloaded from the site
2. the database can be saved (location displayed in the console at start). no export functionality

**Comment by AzmodanRO** [comment]
in version 2.2 there is an import/export functionality in the Journal window. it exports a session at a time to a text file
