### ISSUE TITLE
Shot message json has extra commas after the x and r fields

### ISSUE THREAD

**Issue by mjbedford** [ten-point-nine/freETarget#23]
The message received in json format has a double comma after the x and r fields which make it difficult but not impossible to parse are there. optional fields in the message that are not being sent.

**Comment by ten-point-nine** [comment]
I found that out on Friday

It should be fixed on 3.3.6 which I uploaded on Saturday morning.   If not I’ll fix it tonight

Allan

**Comment by mjbedford** [comment]
Allan , yes you have fixed it I have just upgraded to 3.3.6

**Comment by mjbedford** [comment]
fixed in 3.3.6
