### ISSUE TITLE
Motor paper connect port

### ISSUE THREAD

**Issue by Rebelmuzick** [ten-point-nine/freETarget#8]
Hello everyone, I am Ismael Barone I a member of the 10.9 group on facebook, I am starting this wonderful project, check the J2 connection port on the targetboard is the paper output connector motor? If so, how does it connect?

**Comment by ten-point-nine** [comment]
The accessory connector grounds one of the logic pins to signal a motor to turn.

I’ll update the documentation with instructions.

Allan

**Comment by AzmodanRO** [comment]
rev3.0 has a dedicated port for the motor. documentation is on the website
